group:
  repos: |
    silentzco/statamic-akismet
    silentzco/statamic-charge
    silentzco/statamic-mailchimp
    transformstudios/simple-addon
    transformstudios/statamic-front
    transformstudios/statamic-events
    transformstudios/statamic-review
  files:
    - .github/workflows/create-draft-release.yml
    - .github/workflows/label-pr.yml
    - .github/workflows/release.yml
    - .github/release-drafter.yml
    - .github/pr-labeler.yml
