group:
  repos: |
    transformstudios/statamic-events
  files:
    - .github/workflows/draft-release.yml
    - .github/workflows/label-pr.yml
    - .github/workflows/update-changelog.yml
    - .github/pr-labeler.yml
    - .github/release-drafter.yml
